modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "hudmanager"
version = "${version}"
displayName = "HUD Manager"
description = '''Manages HUD elements gracefully.'''
authors = "i5wear"
credits = "Ferinjoque"
displayURL = "https://modrinth.com/mod/HUD-Manager"
logoFile = "assets/hudmanager/icon.png"

[[mixins]]
config = "hudmanager.mixins.json"

[[dependencies.hudmanager]]
modId = "minecraft"
versionRange = "[26.1,)"

[[dependencies.hudmanager]]
modId = "neoforge"
versionRange = "[26.1,)"